version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bgremover_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: bgremover_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
