# docker-compose.yml
version: '3.8'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bgremover_web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app                # optional, for live code reload
    ports:
      - "8000:8000"
    environment:
      # point your app at the redis service
      - REDIS_URL=redis://redis:6379/0
      # FastAPI secrets etc. can go here or in a .env file
      #- SECRET_KEY=supersecret
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: bgremover_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # -- Optional: if you have Celery tasks or RQ jobs --
  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: bgremover_worker
  #   command: celery -A app.worker.celery_app worker --loglevel=info
  #   environment:
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - redis
